// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB7AltRglMD72CHty6inv0bu2sLkcZM7E',
    appId: '1:289868045508:web:1b2988e8263ac66c99fd91',
    messagingSenderId: '289868045508',
    projectId: 'rfqinsights',
    authDomain: 'rfqinsights.firebaseapp.com',
    storageBucket: 'rfqinsights.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB77RKn5XPGFLIY7hczmJOHmERWN3Fk0hQ',
    appId: '1:289868045508:android:8f0f746f2e31102b99fd91',
    messagingSenderId: '289868045508',
    projectId: 'rfqinsights',
    storageBucket: 'rfqinsights.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYwhUM5GVaJq0uKoL_0VmMYZN4zZJXgJ4',
    appId: '1:289868045508:ios:71970eaebe82631299fd91',
    messagingSenderId: '289868045508',
    projectId: 'rfqinsights',
    storageBucket: 'rfqinsights.firebasestorage.app',
    iosBundleId: 'com.example.rfqInsights',
  );
}
